name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

env:
  cache_nonce: 0 # Allows for easily busting actions/cache caches
  nim_version: v2.0.14

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
      cache_nonce: ${{ env.cache_nonce }}
    steps:
      - name: Compute matrix
        id: matrix
        uses: fabiocaccamo/create-matrix-action@v4
        with:
          matrix: |
            os {windows}, cpu {amd64}, builder {windows-latest}, tests {contract},    nim_version {${{ env.nim_version }}}, shell {msys2}

  build:
    needs: matrix
    uses: ./.github/workflows/ci-reusable.yml
    with:
      matrix: ${{ needs.matrix.outputs.matrix }}
      cache_nonce: ${{ needs.matrix.outputs.cache_nonce }}
